-- Run once in Supabase → SQL Editor on the LIVE project, after 002_orders_and_admin.sql.
-- Brings the database catalog in line with the site: 18 products, 6 collections.
-- Generated from js/data.js. Safe to re-run: it updates rows in place and keeps orders untouched.
-- Stock is reset to the numbers in js/data.js, so re-run it only before real orders arrive.

BEGIN;

-- Product fields the site shows that the table did not have yet
ALTER TABLE products ADD COLUMN IF NOT EXISTS story TEXT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS motif TEXT;

-- 1. COLLECTIONS ------------------------------------------------------------
INSERT INTO collections (name, slug, description, is_active, display_order) VALUES
  ($q$ALL$q$, $q$all$q$, $q$Every Bravadian design in one place. Oversized 240 GSM cotton tees with original Indian artwork.$q$, true, 0),
  ($q$ANIME$q$, $q$anime$q$, $q$Anime characters, manga-inspired artwork, Japanese animation.$q$, true, 1),
  ($q$MYTHOLOGY$q$, $q$mythology$q$, $q$Krishna, Shiva, Hanuman, Ramayana, Mahabharata, deities, mythological stories.$q$, true, 2),
  ($q$HERITAGE$q$, $q$heritage$q$, $q$Indian crafts, folk art, traditional patterns, architecture, cultural symbols, regional traditions.$q$, true, 3),
  ($q$STREET CULTURE$q$, $q$street-culture$q$, $q$Graffiti, urban graphics, hip-hop, typography, rebellious/contemporary designs.$q$, true, 4),
  ($q$MINIMAL$q$, $q$minimal$q$, $q$Simple typography, subtle symbols, clean graphics, understated designs.$q$, true, 5)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, description = EXCLUDED.description,
  is_active = EXCLUDED.is_active, display_order = EXCLUDED.display_order, updated_at = NOW();

-- 2. PRODUCTS ---------------------------------------------------------------
INSERT INTO products (id, name, slug, description, story, motif, price, compare_price, launch_price,
  collection_slug, tags, fabric, gsm, fit, material, sku, is_featured, is_new_drop, is_coming_soon,
  relic_tag, relic_badge, images, variants, status) VALUES
  ($q$prod-018$q$, $q$TRINETRA TEE$q$, $q$trinetra-tee$q$, $q$Shiva's third eye rising over the Himalaya, circled by the moon and the words See Beyond, printed large across the back, with a small BRAVADIAN mark on the front left chest. Oversized 240 GSM French Terry cotton, bio + silicone washed, DTF print.$q$, $q$Past, present, future, within. The third eye sees what the other two miss. A reminder to look past the obvious.$q$, NULL, 699, 999, NULL, $q$mythology$q$, ARRAY[$q$trinetra$q$, $q$shiva$q$, $q$third eye$q$, $q$mythology$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-TRN-06$q$, true, true, false, $q$DESIGN 06$q$, $q$NEW DROP$q$, $q${"front":"/images/products/trinetra/preview.webp"}$q$::jsonb, $q$[{"color":"Black","size":"S","stock":10},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":10},{"color":"Black","size":"XL","stock":10},{"color":"Black","size":"XXL","stock":10},{"color":"White","size":"S","stock":10},{"color":"White","size":"M","stock":10},{"color":"White","size":"L","stock":10},{"color":"White","size":"XL","stock":10},{"color":"White","size":"XXL","stock":10}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-017$q$, $q$HARA HARA MAHADEVA TEE$q$, $q$hara-hara-mahadeva-tee$q$, $q$Om Namah Shivaya in Devanagari beneath a trishul, printed as one vertical strip on the left chest, over the heart. Plain back. Oversized 240 GSM French Terry cotton, bio + silicone washed, DTF print.$q$, $q$A chant worn close to the heart. The trishul leads and the five syllables follow, running down the left chest like a quiet prayer.$q$, NULL, 699, 999, NULL, $q$mythology$q$, ARRAY[$q$shiva$q$, $q$om namah shivaya$q$, $q$trishul$q$, $q$mythology$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-HHM-05$q$, true, true, false, $q$DESIGN 05$q$, $q$NEW DROP$q$, $q${"front":"/images/products/hara-hara-mahadeva/black-front.webp","closeup":"/images/products/hara-hara-mahadeva/black-closeup.webp","lifestyle":"/images/products/hara-hara-mahadeva/black-model.webp","lifestyle2":"/images/products/hara-hara-mahadeva/black-model2.webp","colors":{"Black":{"front":"/images/products/hara-hara-mahadeva/black-front.webp","model":"/images/products/hara-hara-mahadeva/black-model.webp","model2":"/images/products/hara-hara-mahadeva/black-model2.webp","closeup":"/images/products/hara-hara-mahadeva/black-closeup.webp"},"Ivory":{"front":"/images/products/hara-hara-mahadeva/ivory-front.webp","model":"/images/products/hara-hara-mahadeva/ivory-model.webp"},"Red":{"front":"/images/products/hara-hara-mahadeva/red-front.webp","model":"/images/products/hara-hara-mahadeva/red-model.webp"},"Royal Blue":{"front":"/images/products/hara-hara-mahadeva/royal-blue-front.webp","model":"/images/products/hara-hara-mahadeva/royal-blue-model.webp"},"White":{"front":"/images/products/hara-hara-mahadeva/white-front.webp","model":"/images/products/hara-hara-mahadeva/white-model.webp"}}}$q$::jsonb, $q$[{"color":"Black","size":"S","stock":10},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":10},{"color":"Black","size":"XL","stock":10},{"color":"Black","size":"XXL","stock":10},{"color":"Ivory","size":"S","stock":10},{"color":"Ivory","size":"M","stock":10},{"color":"Ivory","size":"L","stock":10},{"color":"Ivory","size":"XL","stock":10},{"color":"Ivory","size":"XXL","stock":10},{"color":"Red","size":"S","stock":10},{"color":"Red","size":"M","stock":10},{"color":"Red","size":"L","stock":10},{"color":"Red","size":"XL","stock":10},{"color":"Red","size":"XXL","stock":10},{"color":"Royal Blue","size":"S","stock":10},{"color":"Royal Blue","size":"M","stock":10},{"color":"Royal Blue","size":"L","stock":10},{"color":"Royal Blue","size":"XL","stock":10},{"color":"Royal Blue","size":"XXL","stock":10},{"color":"White","size":"S","stock":10},{"color":"White","size":"M","stock":10},{"color":"White","size":"L","stock":10},{"color":"White","size":"XL","stock":10},{"color":"White","size":"XXL","stock":10}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-016$q$, $q$GANESHA TEE$q$, $q$ganesha-tee$q$, $q$Lord Ganesha seated before a red sun, with Om and Vakratunda in brush-stroke Devanagari. Oversized 240 GSM French Terry cotton, bio + silicone washed, DTF back print.$q$, $q$The remover of obstacles, drawn in ink and red. For every new start.$q$, NULL, 699, 999, NULL, $q$mythology$q$, ARRAY[$q$ganesha$q$, $q$vakratunda$q$, $q$om$q$, $q$mythology$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-GNS-04$q$, true, true, false, $q$DESIGN 04$q$, $q$NEW DROP$q$, $q${"front":"/images/products/ganesha/preview.webp"}$q$::jsonb, $q$[{"color":"Black","size":"S","stock":10},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":10},{"color":"Black","size":"XL","stock":10},{"color":"Black","size":"XXL","stock":10}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-015$q$, $q$BORN TO RISE TEE$q$, $q$born-to-rise-tee$q$, $q$A black eagle with blazing red wings under the words Born to Rise, printed large across the back, with a small BRAVADIAN mark on the front left chest. Oversized 240 GSM French Terry cotton, bio + silicone washed, DTF print.$q$, $q$For the days you start again. An eagle rises against the wind, not away from it.$q$, NULL, 699, 999, NULL, $q$street-culture$q$, ARRAY[$q$eagle$q$, $q$born to rise$q$, $q$street culture$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-BTR-03$q$, true, true, false, $q$DESIGN 03$q$, $q$NEW DROP$q$, $q${"front":"/images/products/born-to-rise/black-back.webp","closeup":"/images/products/born-to-rise/black-closeup.webp","lifestyle":"/images/products/born-to-rise/black-model.webp","lifestyle2":"/images/products/born-to-rise/white-model.webp","colors":{"Black":{"front":"/images/products/born-to-rise/black-back.webp","model":"/images/products/born-to-rise/black-model.webp","closeup":"/images/products/born-to-rise/black-closeup.webp"},"White":{"front":"/images/products/born-to-rise/white-back.webp","model":"/images/products/born-to-rise/white-model.webp","closeup":"/images/products/born-to-rise/white-closeup.webp"}}}$q$::jsonb, $q$[{"color":"Black","size":"S","stock":10},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":10},{"color":"Black","size":"XL","stock":10},{"color":"Black","size":"XXL","stock":10},{"color":"White","size":"S","stock":10},{"color":"White","size":"M","stock":10},{"color":"White","size":"L","stock":10},{"color":"White","size":"XL","stock":10},{"color":"White","size":"XXL","stock":10}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-014$q$, $q$INDIAN CRAFT ATLAS TEE$q$, $q$indian-craft-atlas-tee$q$, $q$A map of India drawn in its crafts. Kalamkari, Warli, Madhubani, Pattachitra, Phad, Gond, Cheriyal, Pichwai and Ikat come together around one elephant. Oversized 240 GSM French Terry cotton, bio + silicone washed, DTF back print.$q$, $q$People, patterns, places, purpose. India lives in its crafts, and every region adds a pattern of its own. This design puts a dozen of them on one elephant, with the names listed alongside so you know what you are wearing.$q$, $q$Kalamkari from Andhra Pradesh, Warli from Maharashtra, Madhubani from Bihar, Pattachitra from Odisha, Phad from Rajasthan, Gond from Madhya Pradesh, Cheriyal from Telangana, Pichwai from Nathdwara, Ikat from Odisha and Telangana, and more.$q$, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$oversized$q$, $q$heritage$q$, $q$crafts$q$, $q$kalamkari$q$, $q$madhubani$q$, $q$warli$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-ICA-02$q$, true, true, false, $q$DESIGN 02$q$, $q$NEW DROP$q$, $q${"front":"/images/products/craft-atlas/back-print.webp?v=2","closeup":"/images/products/craft-atlas/closeup.webp","lifestyle":"/images/lookbook/lb-look-02.webp"}$q$::jsonb, $q$[{"color":"Black","size":"S","stock":10},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":10},{"color":"Black","size":"XL","stock":10},{"color":"Black","size":"XXL","stock":10},{"color":"White","size":"S","stock":10},{"color":"White","size":"M","stock":10},{"color":"White","size":"L","stock":10},{"color":"White","size":"XL","stock":10},{"color":"White","size":"XXL","stock":10},{"color":"Red","size":"S","stock":10},{"color":"Red","size":"M","stock":10},{"color":"Red","size":"L","stock":10},{"color":"Red","size":"XL","stock":10},{"color":"Red","size":"XXL","stock":10},{"color":"Royal Blue","size":"S","stock":10},{"color":"Royal Blue","size":"M","stock":10},{"color":"Royal Blue","size":"L","stock":10},{"color":"Royal Blue","size":"XL","stock":10},{"color":"Royal Blue","size":"XXL","stock":10}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-013$q$, $q$BHARAT SPIRIT TEE$q$, $q$bharat-spirit-tee$q$, $q$The peacock, the tiger, the lotus and the elephant, four symbols of India drawn together as one story. Oversized 240 GSM French Terry cotton, bio + silicone washed, with a large DTF back print and the Bi mark on the chest.$q$, $q$Four symbols every Indian grows up with, drawn as one living composition. Built around the idea that pride in where you come from can be worn every day, not saved for special occasions.$q$, $q$Peacock, the national bird, for grace. Tiger, the national animal, for courage. Lotus, the national flower, for rising clean from the mud. Elephant, the national heritage animal, for memory and strength.$q$, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$oversized$q$, $q$heritage$q$, $q$peacock$q$, $q$tiger$q$, $q$lotus$q$, $q$elephant$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-BHS-01$q$, true, true, false, $q$DESIGN 01$q$, $q$NEW DROP$q$, $q${"front":"/images/products/bharat-spirit/back-print.webp","back":"/images/products/bharat-spirit/front.webp","closeup":"/images/products/bharat-spirit/closeup.webp","lifestyle":"/images/products/bharat-spirit/worn-studio.webp?v=2","lifestyle2":"/images/products/bharat-spirit/worn-temple.webp?v=3"}$q$::jsonb, $q$[{"color":"Black","size":"S","stock":10},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":10},{"color":"Black","size":"XL","stock":10},{"color":"Black","size":"XXL","stock":10},{"color":"White","size":"S","stock":10},{"color":"White","size":"M","stock":10},{"color":"White","size":"L","stock":10},{"color":"White","size":"XL","stock":10},{"color":"White","size":"XXL","stock":10},{"color":"Red","size":"S","stock":10},{"color":"Red","size":"M","stock":10},{"color":"Red","size":"L","stock":10},{"color":"Red","size":"XL","stock":10},{"color":"Red","size":"XXL","stock":10},{"color":"Royal Blue","size":"S","stock":10},{"color":"Royal Blue","size":"M","stock":10},{"color":"Royal Blue","size":"L","stock":10},{"color":"Royal Blue","size":"XL","stock":10},{"color":"Royal Blue","size":"XXL","stock":10}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-001$q$, $q$HOYSALA OVERSIZED RELIC TEE$q$, $q$hoysala-oversized-relic-tee$q$, $q$A severe tactical garment engineered from 240 GSM heavyweight French Terry. Imprinted with sacred architectural friezes from the historic Halebidu temple complex, modified as modern metropolitan armor.$q$, NULL, NULL, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$oversized$q$, $q$hoysala$q$, $q$heavyweight$q$, $q$280gsm$q$, $q$heritage$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized Boxy$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-HYS-01$q$, true, true, false, $q$DESIGN 01$q$, $q$NEW DROP$q$, NULL, $q$[{"color":"Black","size":"S","stock":8},{"color":"Black","size":"M","stock":15},{"color":"Black","size":"L","stock":12},{"color":"Black","size":"XL","stock":6},{"color":"Black","size":"XXL","stock":4},{"color":"White","size":"S","stock":4},{"color":"White","size":"M","stock":8},{"color":"White","size":"L","stock":6},{"color":"White","size":"XL","stock":0},{"color":"White","size":"XXL","stock":2},{"color":"Red","size":"S","stock":8},{"color":"Red","size":"M","stock":15},{"color":"Red","size":"L","stock":12},{"color":"Red","size":"XL","stock":6},{"color":"Red","size":"XXL","stock":4},{"color":"Royal Blue","size":"S","stock":8},{"color":"Royal Blue","size":"M","stock":15},{"color":"Royal Blue","size":"L","stock":12},{"color":"Royal Blue","size":"XL","stock":6},{"color":"Royal Blue","size":"XXL","stock":4}]$q$::jsonb, $q$DRAFT$q$),
  ($q$prod-002$q$, $q$HOYSALA LINGESHWARA RELIC TEE$q$, $q$hoysala-lingeshwara-relic-tee$q$, $q$Engineered boxy heavyweight silhouette featuring the sacred Lingeshwara stone sanctuary geometry across dropped shoulder lines.$q$, NULL, NULL, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$heritage$q$, $q$hoysala$q$, $q$lingeshwara$q$, $q$heavyweight$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Boxy Drop Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-LNG-02$q$, true, true, false, $q$DESIGN 02$q$, $q$NEW DROP$q$, NULL, $q$[{"color":"Black","size":"S","stock":6},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":8},{"color":"Black","size":"XL","stock":4},{"color":"Black","size":"XXL","stock":3},{"color":"White","size":"S","stock":6},{"color":"White","size":"M","stock":10},{"color":"White","size":"L","stock":8},{"color":"White","size":"XL","stock":4},{"color":"White","size":"XXL","stock":3},{"color":"Red","size":"S","stock":6},{"color":"Red","size":"M","stock":10},{"color":"Red","size":"L","stock":8},{"color":"Red","size":"XL","stock":4},{"color":"Red","size":"XXL","stock":3},{"color":"Royal Blue","size":"S","stock":6},{"color":"Royal Blue","size":"M","stock":10},{"color":"Royal Blue","size":"L","stock":8},{"color":"Royal Blue","size":"XL","stock":4},{"color":"Royal Blue","size":"XXL","stock":3}]$q$::jsonb, $q$DRAFT$q$),
  ($q$prod-003$q$, $q$SRI YOGA SARASVATHESHWARA TEE$q$, $q$sri-yoga-sarasvatheshwara-tee$q$, $q$Oversized 240 GSM cotton tee with a golden print of the many-armed goddess of learning.$q$, NULL, NULL, 699, 999, NULL, $q$mythology$q$, ARRAY[$q$mythology$q$, $q$deities$q$, $q$krishna$q$, $q$shiva$q$, $q$gold-foil$q$, $q$300gsm$q$, $q$yoga$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Architectural Boxy$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-YOG-03$q$, true, true, false, $q$DESIGN 03$q$, $q$NEW DROP$q$, NULL, $q$[{"color":"Black","size":"S","stock":7},{"color":"Black","size":"M","stock":12},{"color":"Black","size":"L","stock":9},{"color":"Black","size":"XL","stock":5},{"color":"Black","size":"XXL","stock":3},{"color":"White","size":"S","stock":7},{"color":"White","size":"M","stock":12},{"color":"White","size":"L","stock":9},{"color":"White","size":"XL","stock":5},{"color":"White","size":"XXL","stock":3},{"color":"Red","size":"S","stock":7},{"color":"Red","size":"M","stock":12},{"color":"Red","size":"L","stock":9},{"color":"Red","size":"XL","stock":5},{"color":"Red","size":"XXL","stock":3},{"color":"Royal Blue","size":"S","stock":7},{"color":"Royal Blue","size":"M","stock":12},{"color":"Royal Blue","size":"L","stock":9},{"color":"Royal Blue","size":"XL","stock":5},{"color":"Royal Blue","size":"XXL","stock":3}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-004$q$, $q$NRITYA PRIMACY DESCENSION JACKET$q$, $q$nritya-primacy-descension-jacket$q$, $q$Heavyweight tactical bomber constructed in 450 GSM canvas shell with custom antique brass zippers, rib knit cuffs, and tonal warrior embroidery.$q$, NULL, NULL, 6500, 9999, NULL, $q$heritage$q$, ARRAY[$q$heritage$q$, $q$indian-craft$q$, $q$jacket$q$, $q$bomber$q$, $q$nritya$q$, $q$450gsm$q$]::TEXT[], $q$450 GSM DUCK CANVAS // BOMBER ARCHITECTURE$q$, 450, $q$Bomber Flight Cut$q$, $q$450 GSM Heavy Canvas & Satin Lining$q$, $q$BRVD-NRT-04$q$, true, true, false, $q$DESIGN 04$q$, $q$NEW DROP$q$, NULL, $q$[{"color":"Black","size":"S","stock":5},{"color":"Black","size":"M","stock":8},{"color":"Black","size":"L","stock":6},{"color":"Black","size":"XL","stock":3},{"color":"Black","size":"XXL","stock":2}]$q$::jsonb, $q$DRAFT$q$),
  ($q$prod-005$q$, $q$ASURA SOLAR FIRE OVERSIZED TEE$q$, $q$asura-solar-fire-oversized-tee$q$, $q$Charcoal oversized tee with the Sanskrit line "ॐ सह नाववतु" and a blazing sun printed large on the back.$q$, NULL, NULL, 699, 999, NULL, $q$mythology$q$, ARRAY[$q$mythology$q$, $q$shiva$q$, $q$ramayana$q$, $q$solar-fire$q$, $q$280gsm$q$, $q$oversized$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Relaxed Drop-Shoulder$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-ASR-05$q$, true, true, false, $q$DESIGN 05$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":7},{"color":"Black","size":"M","stock":11},{"color":"Black","size":"L","stock":8},{"color":"Black","size":"XL","stock":4},{"color":"Black","size":"XXL","stock":2},{"color":"White","size":"S","stock":7},{"color":"White","size":"M","stock":11},{"color":"White","size":"L","stock":8},{"color":"White","size":"XL","stock":4},{"color":"White","size":"XXL","stock":2},{"color":"Red","size":"S","stock":7},{"color":"Red","size":"M","stock":11},{"color":"Red","size":"L","stock":8},{"color":"Red","size":"XL","stock":4},{"color":"Red","size":"XXL","stock":2},{"color":"Royal Blue","size":"S","stock":7},{"color":"Royal Blue","size":"M","stock":11},{"color":"Royal Blue","size":"L","stock":8},{"color":"Royal Blue","size":"XL","stock":4},{"color":"Royal Blue","size":"XXL","stock":2}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-006$q$, $q$BERUNDA DUAL VISION ARMOR TEE$q$, $q$berunda-dual-vision-armor-tee$q$, $q$240 GSM heavyweight cotton tee with monumental twin-headed Gandaberunda imperial crest rendered in antique gold embroidery.$q$, NULL, NULL, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$heritage$q$, $q$berunda$q$, $q$traditional-patterns$q$, $q$cultural-symbols$q$, $q$embroidery$q$, $q$280gsm$q$, $q$armor$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-BRD-06$q$, true, true, true, $q$DESIGN 06$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":5},{"color":"Black","size":"M","stock":8},{"color":"Black","size":"L","stock":6},{"color":"Black","size":"XL","stock":3},{"color":"Black","size":"XXL","stock":2},{"color":"White","size":"S","stock":5},{"color":"White","size":"M","stock":8},{"color":"White","size":"L","stock":6},{"color":"White","size":"XL","stock":3},{"color":"White","size":"XXL","stock":2},{"color":"Red","size":"S","stock":5},{"color":"Red","size":"M","stock":8},{"color":"Red","size":"L","stock":6},{"color":"Red","size":"XL","stock":3},{"color":"Red","size":"XXL","stock":2},{"color":"Royal Blue","size":"S","stock":5},{"color":"Royal Blue","size":"M","stock":8},{"color":"Royal Blue","size":"L","stock":6},{"color":"Royal Blue","size":"XL","stock":3},{"color":"Royal Blue","size":"XXL","stock":2}]$q$::jsonb, $q$DRAFT$q$),
  ($q$prod-007$q$, $q$BRAVADIAN NINETAILS$q$, $q$bravadian-ninetails$q$, $q$Oversized 240 GSM cotton tee with a large back print of the nine-tailed fox spirit from old legends.$q$, NULL, NULL, 699, 999, NULL, $q$anime$q$, ARRAY[$q$anime$q$, $q$manga$q$, $q$japanese-animation$q$, $q$ninetails$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-NT-07$q$, false, false, true, $q$DESIGN 07$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":8},{"color":"Black","size":"M","stock":12},{"color":"Black","size":"L","stock":0},{"color":"Black","size":"XL","stock":5},{"color":"Black","size":"XXL","stock":2},{"color":"White","size":"S","stock":0},{"color":"White","size":"M","stock":6},{"color":"White","size":"L","stock":9},{"color":"White","size":"XL","stock":4},{"color":"White","size":"XXL","stock":1},{"color":"Red","size":"S","stock":8},{"color":"Red","size":"M","stock":12},{"color":"Red","size":"L","stock":0},{"color":"Red","size":"XL","stock":5},{"color":"Red","size":"XXL","stock":2},{"color":"Royal Blue","size":"S","stock":8},{"color":"Royal Blue","size":"M","stock":12},{"color":"Royal Blue","size":"L","stock":0},{"color":"Royal Blue","size":"XL","stock":5},{"color":"Royal Blue","size":"XXL","stock":2}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-008$q$, $q$BRAVADIAN GARUDA REBEL$q$, $q$bravadian-garuda-rebel$q$, $q$Garuda, the eagle of Indian mythology, printed wing to wing across the back of an oversized 240 GSM cotton tee.$q$, NULL, NULL, 699, 999, NULL, $q$mythology$q$, ARRAY[$q$mythology$q$, $q$garuda$q$, $q$deities$q$, $q$mythological-stories$q$, $q$heavyweight$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-GRD-08$q$, true, false, true, $q$DESIGN 08$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":7},{"color":"Black","size":"M","stock":10},{"color":"Black","size":"L","stock":4},{"color":"Black","size":"XL","stock":3},{"color":"Black","size":"XXL","stock":0},{"color":"White","size":"S","stock":5},{"color":"White","size":"M","stock":8},{"color":"White","size":"L","stock":6},{"color":"White","size":"XL","stock":0},{"color":"White","size":"XXL","stock":3},{"color":"Red","size":"S","stock":5},{"color":"Red","size":"M","stock":8},{"color":"Red","size":"L","stock":6},{"color":"Red","size":"XL","stock":0},{"color":"Red","size":"XXL","stock":3},{"color":"Royal Blue","size":"S","stock":5},{"color":"Royal Blue","size":"M","stock":8},{"color":"Royal Blue","size":"L","stock":6},{"color":"Royal Blue","size":"XL","stock":0},{"color":"Royal Blue","size":"XXL","stock":3}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-009$q$, $q$BRAVADIAN MONOLITH BHARAT$q$, $q$bravadian-monolith-bharat$q$, $q$Rooted in Indian soil. A clean oversized tee with the Ashoka chakra and the coordinates of Delhi on the back.$q$, NULL, NULL, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$heritage$q$, $q$bharat$q$, $q$architecture$q$, $q$cultural-symbols$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-BHT-09$q$, true, true, true, $q$DESIGN 09$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":12},{"color":"Black","size":"M","stock":15},{"color":"Black","size":"L","stock":8},{"color":"Black","size":"XL","stock":6},{"color":"Black","size":"XXL","stock":4},{"color":"White","size":"S","stock":6},{"color":"White","size":"M","stock":7},{"color":"White","size":"L","stock":5},{"color":"White","size":"XL","stock":0},{"color":"White","size":"XXL","stock":2},{"color":"Red","size":"S","stock":12},{"color":"Red","size":"M","stock":15},{"color":"Red","size":"L","stock":8},{"color":"Red","size":"XL","stock":6},{"color":"Red","size":"XXL","stock":4},{"color":"Royal Blue","size":"S","stock":12},{"color":"Royal Blue","size":"M","stock":15},{"color":"Royal Blue","size":"L","stock":8},{"color":"Royal Blue","size":"XL","stock":6},{"color":"Royal Blue","size":"XXL","stock":4}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-010$q$, $q$BRAVADIAN CYBER REBEL$q$, $q$bravadian-cyber-rebel$q$, $q$Loud street typography inspired by Indian city walls, printed on an oversized 240 GSM cotton tee.$q$, NULL, NULL, 699, 999, NULL, $q$street-culture$q$, ARRAY[$q$street-culture$q$, $q$typography$q$, $q$graffiti$q$, $q$urban$q$, $q$rebellious$q$, $q$oversized$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-CR-10$q$, false, false, true, $q$DESIGN 10$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":4},{"color":"Black","size":"M","stock":6},{"color":"Black","size":"L","stock":3},{"color":"Black","size":"XL","stock":2},{"color":"Black","size":"XXL","stock":0},{"color":"White","size":"S","stock":4},{"color":"White","size":"M","stock":6},{"color":"White","size":"L","stock":3},{"color":"White","size":"XL","stock":2},{"color":"White","size":"XXL","stock":0},{"color":"Red","size":"S","stock":4},{"color":"Red","size":"M","stock":6},{"color":"Red","size":"L","stock":3},{"color":"Red","size":"XL","stock":2},{"color":"Red","size":"XXL","stock":0},{"color":"Royal Blue","size":"S","stock":4},{"color":"Royal Blue","size":"M","stock":6},{"color":"Royal Blue","size":"L","stock":3},{"color":"Royal Blue","size":"XL","stock":2},{"color":"Royal Blue","size":"XXL","stock":0}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-011$q$, $q$BRAVADIAN ESSENTIAL 240$q$, $q$bravadian-essential-240$q$, $q$No graphics, just a great tee. Thick rib collar, dropped shoulders and a relaxed oversized fit in 240 GSM cotton.$q$, NULL, NULL, 699, 999, NULL, $q$minimal$q$, ARRAY[$q$minimal$q$, $q$essential$q$, $q$clean-graphics$q$, $q$understated$q$, $q$simple-typography$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-ES-11$q$, false, false, true, $q$DESIGN 11$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":20},{"color":"Black","size":"M","stock":25},{"color":"Black","size":"L","stock":18},{"color":"Black","size":"XL","stock":15},{"color":"Black","size":"XXL","stock":8},{"color":"White","size":"S","stock":10},{"color":"White","size":"M","stock":14},{"color":"White","size":"L","stock":9},{"color":"White","size":"XL","stock":5},{"color":"White","size":"XXL","stock":4},{"color":"Red","size":"S","stock":20},{"color":"Red","size":"M","stock":25},{"color":"Red","size":"L","stock":18},{"color":"Red","size":"XL","stock":15},{"color":"Red","size":"XXL","stock":8},{"color":"Royal Blue","size":"S","stock":20},{"color":"Royal Blue","size":"M","stock":25},{"color":"Royal Blue","size":"L","stock":18},{"color":"Royal Blue","size":"XL","stock":15},{"color":"Royal Blue","size":"XXL","stock":8}]$q$::jsonb, $q$PUBLISHED$q$),
  ($q$prod-012$q$, $q$BRAVADIAN ASHOKA EMBER$q$, $q$bravadian-ashoka-ember$q$, $q$The 24-spoke Ashoka chakra in glowing ember orange across the chest and back of an oversized cotton tee.$q$, NULL, NULL, 699, 999, NULL, $q$heritage$q$, ARRAY[$q$heritage$q$, $q$ashoka$q$, $q$cultural-symbols$q$, $q$traditional-patterns$q$, $q$limited$q$, $q$240gsm$q$]::TEXT[], $q$240 GSM FRENCH TERRY // BIO + SILICONE WASH$q$, 240, $q$Oversized$q$, $q$240 GSM French Terry Cotton, Bio + Silicone Washed$q$, $q$BRVD-ASH-12$q$, true, true, true, $q$DESIGN 12$q$, $q$COMING SOON$q$, NULL, $q$[{"color":"Black","size":"S","stock":5},{"color":"Black","size":"M","stock":7},{"color":"Black","size":"L","stock":4},{"color":"Black","size":"XL","stock":0},{"color":"Black","size":"XXL","stock":2},{"color":"White","size":"S","stock":5},{"color":"White","size":"M","stock":7},{"color":"White","size":"L","stock":4},{"color":"White","size":"XL","stock":0},{"color":"White","size":"XXL","stock":2},{"color":"Red","size":"S","stock":5},{"color":"Red","size":"M","stock":7},{"color":"Red","size":"L","stock":4},{"color":"Red","size":"XL","stock":0},{"color":"Red","size":"XXL","stock":2},{"color":"Royal Blue","size":"S","stock":5},{"color":"Royal Blue","size":"M","stock":7},{"color":"Royal Blue","size":"L","stock":4},{"color":"Royal Blue","size":"XL","stock":0},{"color":"Royal Blue","size":"XXL","stock":2}]$q$::jsonb, $q$PUBLISHED$q$)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, slug = EXCLUDED.slug, description = EXCLUDED.description,
  story = EXCLUDED.story, motif = EXCLUDED.motif,
  price = EXCLUDED.price, compare_price = EXCLUDED.compare_price, launch_price = EXCLUDED.launch_price,
  collection_slug = EXCLUDED.collection_slug, tags = EXCLUDED.tags, fabric = EXCLUDED.fabric,
  gsm = EXCLUDED.gsm, fit = EXCLUDED.fit, material = EXCLUDED.material, sku = EXCLUDED.sku,
  is_featured = EXCLUDED.is_featured, is_new_drop = EXCLUDED.is_new_drop, is_coming_soon = EXCLUDED.is_coming_soon,
  relic_tag = EXCLUDED.relic_tag, relic_badge = EXCLUDED.relic_badge,
  images = EXCLUDED.images, variants = EXCLUDED.variants, status = EXCLUDED.status, updated_at = NOW();

-- 3. REMOVE OLD STARTER COLLECTIONS (garuda, asura, chola, ...) no product uses any more
DELETE FROM collections c
 WHERE c.slug NOT IN ($q$all$q$, $q$anime$q$, $q$mythology$q$, $q$heritage$q$, $q$street-culture$q$, $q$minimal$q$)
   AND NOT EXISTS (SELECT 1 FROM products p WHERE p.collection_slug = c.slug);

COMMIT;

-- Check: expect 18 products and 6 collections
SELECT (SELECT count(*) FROM products) AS products, (SELECT count(*) FROM collections) AS collections;
